#!/bin/bash
#-- 
#--	Check the qcFlag == 11133222 or qcFlag == 11144222
#--		see the percentage of the flag raised in each file.
#--
#--	@C.Y. Hsu at Texas A&M Univ on 03-11-2019 
rm aaaa
touch aaaa

for fid in *.csv
do
	grep --color=auto -H -E "11133222|11144222|99999999" $fid >> aaaa
done

cat aaaa | cut -d ':' -f1 |uniq -c | sort -n > aaab

if [ -f aaac ]; then rm aaac; fi; touch aaac

echo "#-- Check the qcFlag == 11133222 or 11144222 or 99999999" >> aaac
echo "#-- " >> aaac
echo "#-- Column 01 = file name" >> aaac
echo "#-- Column 02 = occurance percentage" >> aaac
echo "#-- Column 03 = occurance" >> aaac
echo "#-- Column 04 = total num of data" >> aaac
echo "#-- " >> aaac
echo -e "\t\t\t file name \t\t\t\t\t percent  error  total" >> aaac

for fid in `cat aaab | awk '{print $2}'`
do 
	total_num=`cat $fid |wc -l`
	error_num=`grep $fid aaab | awk '{print $1}'`
	error_per=`echo "${error_num}/${total_num} *100.0" |bc -l| xargs printf %4.2f`
	printf "%-70s \t %05.2f%%   %5d  %5d\n" $fid $error_per $error_num $total_num >>aaac
done

